name: ie-bank-backend

on:
  push:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  # Backend apps
  BACKEND_WEBAPP_DEV: money404-be-dev
  BACKEND_WEBAPP_UAT: money404-be-uat
  # Container registry details
  SUBSCRIPTION_ID_DEV: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
  DOCKER_REGISTRY_SERVER_URL_DEV: money404acrdev.azurecr.io
  DOCKER_REGISTRY_SERVER_URL_UAT: money404acruat.azurecr.io
  IMAGE_NAME_DEV: money404-be-dev
  IMAGE_NAME_UAT: money404-be-uat

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENV: ghci
    steps:
      - uses: actions/checkout@v3

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Get docker registry credentials from Azure Key Vault
        uses: azure/CLI@v1
        with:
          inlineScript: |
            REGISTRY_USERNAME_DEV=$(az keyvault secret show --name keyVaultSecretNameAdminUsername --vault-name money404-kv-dev --query value -o tsv)
            REGISTRY_PASSWORD_DEV=$(az keyvault secret show --name keyVaultSecretNameAdminPassword0 --vault-name money404-kv-dev --query value -o tsv)
            echo "REGISTRY_USERNAME_DEV=$REGISTRY_USERNAME_DEV" >> $GITHUB_ENV
            echo "REGISTRY_PASSWORD_DEV=$REGISTRY_PASSWORD_DEV" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Azure Container Registry (Dev)
        uses: azure/docker-login@v2
        with:
          login-server: ${{ env.DOCKER_REGISTRY_SERVER_URL_DEV }}
          username: ${{ env.REGISTRY_USERNAME_DEV }}
          password: ${{ env.REGISTRY_PASSWORD_DEV }}

      - name: Build Docker image (Dev)
        run: |
          docker build -t ${{ env.DOCKER_REGISTRY_SERVER_URL_DEV }}/${{ env.IMAGE_NAME_DEV }}:${{ github.sha }} .

      - name: Push Docker image to Azure Container Registry (Dev)
        run: |
          docker push ${{ env.DOCKER_REGISTRY_SERVER_URL_DEV }}/${{ env.IMAGE_NAME_DEV }}:${{ github.sha }}

  deploy-dev:
    # Deploy to any branch other than main on a push, or to main on PR merge
    if: github.event_name == 'push' && github.ref != 'refs/heads/main' || (github.event_name == 'pull_request' && github.base_ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'

    steps:
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App - Dev
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: ${{ env.BACKEND_WEBAPP_DEV }}
          images: ${{ env.DOCKER_REGISTRY_SERVER_URL_DEV }}/${{ env.IMAGE_NAME_DEV }}:${{ github.sha }}

  deploy-uat:
    # Deploy to UAT if there is a push to main (after a PR merge)
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'    
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'UAT'

    steps:
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get docker registry credentials from Azure Key Vault (UAT)
        uses: azure/CLI@v1
        with:
          inlineScript: |
            REGISTRY_USERNAME_UAT=$(az keyvault secret show --name keyVaultSecretNameAdminUsername --vault-name money404-kv-uat --query value -o tsv)
            REGISTRY_PASSWORD_UAT=$(az keyvault secret show --name keyVaultSecretNameAdminPassword0 --vault-name money404-kv-uat --query value -o tsv)
            echo "REGISTRY_USERNAME_UAT=$REGISTRY_USERNAME_UAT" >> $GITHUB_ENV
            echo "REGISTRY_PASSWORD_UAT=$REGISTRY_PASSWORD_UAT" >> $GITHUB_ENV

      - name: Log in to Azure Container Registry (UAT)
        uses: azure/docker-login@v2
        with:
          login-server: ${{ env.DOCKER_REGISTRY_SERVER_URL_UAT }}
          username: ${{ env.REGISTRY_USERNAME_UAT }}
          password: ${{ env.REGISTRY_PASSWORD_UAT }}

      - name: Deploy to Azure Web App - UAT
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.BACKEND_WEBAPP_UAT }}
          images: ${{ env.DOCKER_REGISTRY_SERVER_URL_UAT }}/${{ env.IMAGE_NAME_UAT }}:${{ github.sha }}
